services:
    hostmanager:
        image: ghcr.io/dkarlovi/docker-hostmanager.rs:1.4.0
        profiles:
            - Linux
        restart: always
        volumes:
            - /etc/hosts:/hosts
            - /var/run/docker.sock:/var/run/docker.sock

    cloudflared:
        image: cloudflare/cloudflared:2026.3.0
        profiles:
            - Linux
        restart: unless-stopped
        user: "0"
        environment:
            HOME: $HOME
        command:
            - --no-autoupdate
            - tunnel
            - run
        volumes:
            - $HOME/.cloudflared:$HOME/.cloudflared:ro
        networks:
            - public

networks:
    public:
        external: true
        name: public
